export const CONSTANT = {
  CARD: 'CARD',
  ITEM_DATA_CARD: 'ITEM_DATA_CARD',
  WIDGET_TYPE_TEXT: 'Text Widget',
  WIDGET_TYPE_DATATABLE: 'Datatable Widget',
  WIDGET_TODO_LIST: 'TODO List',
  WIDGET_SIMPLE_CHART: 'Simple Chart Widget',
  WIDGET_ADD: 'Add Widget',
  ADD_CONTACT_PROPERTY: 'ADD_CONTACT_PROPERTY',
  REMOVE_CONTACT_PROPERTY: 'REMOVE_CONTACT_PROPERTY'
}

export const headerDashBoardConstant = {
  EXPAND_WIDGET: 'EXPAND_WIDGET',
  CLOSE_EXPAND_WIDGET: 'CLOSE_EXPAND_WIDGET'
}

export const WidgetConstant = {
  
}